name: brainiak_env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2=py37hecd8cb5_1001
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py37h67323c0_0
  - brotli=1.0.9=hca72f7f_7
  - brotli-bin=1.0.9=hca72f7f_7
  - ca-certificates=2023.08.22=hecd8cb5_0
  - cctools_osx-64=949.0.1=hc7db93f_25
  - certifi=2022.12.7=py37hecd8cb5_0
  - clang=14.0.6=hecd8cb5_1
  - clang-14=14.0.6=default_hd95374b_1
  - clang_osx-64=14.0.6=hb1e4b1b_0
  - clangxx=14.0.6=default_hd95374b_1
  - clangxx_osx-64=14.0.6=hd8b9576_0
  - compiler-rt=14.0.6=hda8b6b8_0
  - compiler-rt_osx-64=14.0.6=h8d5cb93_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.33=py37hcec6c5f_0
  - debugpy=1.5.1=py37he9d5cce_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py37hecd8cb5_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=hd8bbffd_0
  - giflib=5.2.1=h6c40b1e_3
  - h5py=3.7.0=py37h4a1dd59_0
  - hdf5=1.10.6=hdbbcd12_0
  - intel-openmp=2023.1.0=ha357a0b_43547
  - ipykernel=6.15.2=py37hecd8cb5_0
  - ipython=7.31.1=py37hecd8cb5_1
  - jedi=0.18.1=py37hecd8cb5_1
  - joblib=1.1.1=py37hecd8cb5_0
  - jpeg=9e=h6c40b1e_1
  - jupyter_client=7.4.9=py37hecd8cb5_0
  - jupyter_core=4.11.2=py37hecd8cb5_0
  - kiwisolver=1.3.2=py37he9d5cce_0
  - lcms2=2.12=hf1fd2bf_0
  - ld64_osx-64=530=h70f3046_25
  - ldid=2.1.5=hc58f1be_3
  - lerc=3.0=he9d5cce_0
  - libbrotlicommon=1.0.9=hca72f7f_7
  - libbrotlidec=1.0.9=hca72f7f_7
  - libbrotlienc=1.0.9=hca72f7f_7
  - libclang-cpp14=14.0.6=default_hd95374b_1
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.17=hb664fd8_1
  - libffi=3.4.4=hecd8cb5_0
  - libgfortran=3.0.1=h93005f0_2
  - libllvm14=14.0.6=h91fad77_3
  - libpng=1.6.39=h6c40b1e_0
  - libsodium=1.0.18=h1de35cc_0
  - libtiff=4.5.1=hcec6c5f_0
  - libwebp=1.2.4=hf6ce154_1
  - libwebp-base=1.2.4=h6c40b1e_1
  - llvm-meta=7.0.0=0
  - llvm-openmp=4.0.1=hcfea43d_1
  - llvm-tools=14.0.6=he0576d7_3
  - lz4-c=1.9.4=hcec6c5f_0
  - matplotlib-base=3.5.3=py37hfb0c5b7_0
  - matplotlib-inline=0.1.6=py37hecd8cb5_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37h9ed2024_0
  - mkl_fft=1.3.0=py37ha059aab_0
  - mkl_random=1.1.1=py37h959d312_0
  - mpi=1.0=mpich
  - mpi4py=3.1.4=py37hce9ae6d_0
  - mpich=3.3.2=hc856adb_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.5.6=py37hecd8cb5_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - nibabel=4.0.2=pyhd8ed1ab_0
  - nitime=0.8.1=py37h3b54f70_1
  - numexpr=2.7.3=py37h16bde0e_0
  - numpy=1.19.2=py37h456fd55_0
  - numpy-base=1.19.2=py37hcfb5961_0
  - openmp=7.0.0=h2d50403_0
  - openssl=1.1.1w=hca72f7f_0
  - packaging=22.0=py37hecd8cb5_0
  - pandas=1.3.5=py37h743cdd8_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=0.5.3=py37hecd8cb5_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py37hcec6c5f_0
  - pip=22.3.1=py37hecd8cb5_0
  - prompt-toolkit=3.0.36=py37hecd8cb5_0
  - psutil=5.9.0=py37hca72f7f_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pybind11=2.10.1=py37ha357a0b_0
  - pybind11-global=2.10.1=py37ha357a0b_0
  - pydicom=2.4.3=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyparsing=3.0.9=py37hecd8cb5_0
  - python=3.7.16=h218abb5_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2022.7=py37hecd8cb5_0
  - pyzmq=23.2.0=py37he9d5cce_0
  - readline=8.2=hca72f7f_0
  - scikit-learn=0.22.1=py37h27c97d8_0
  - scipy=1.6.2=py37h2515648_0
  - setuptools=65.6.3=py37hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h6c40b1e_0
  - statsmodels=0.13.5=py37hacda100_1
  - tapi=1000.10.8=ha1b3eb9_0
  - theano=1.0.4=py37h04f5b5a_0
  - tk=8.6.12=h5d9f67b_0
  - tornado=6.2=py37hca72f7f_0
  - traitlets=5.7.1=py37hecd8cb5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=py37hecd8cb5_0
  - xz=5.4.2=h6c40b1e_0
  - zeromq=4.3.4=h23ab428_0
  - zlib=1.2.13=h4dc903c_0
  - zstd=1.5.5=hc035e20_0
  - pip:
    - brainiak==0.11
prefix: /Users/lendlab/opt/anaconda3/envs/brainiak_env
